### PR TITLE
Updated to use flutter_form_builder: 5.0.0-alpha.1

### PR DESCRIPTION
**Pull request by YuenEsc**

### CODE REVIEW

**Comment by YuenEsc** [comment]
Hello Danvick, is there any way we can supoort you to migrate the package (And their dependencies if necesary) to the latest release?

**Comment by yosus** [comment]
is this repo still active ?

**Comment by YuenEsc** [comment]
I'm not sure. What I know is that Danvick has been pretty busy lately

**Comment by haliknihudas666** [comment]
I think you can migrate this repo to support null safety :D last month ive submitted a pull request on form_builder_phone_field and got merged :D just create a pull request :D

**Pull request merged**
